# Generated by Django 5.1.1 on 2024-10-16 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Categoria')),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('conteudo', models.TextField(max_length=3000, verbose_name='Conteúdo')),
                ('criada_em', models.DateTimeField(auto_now_add=True, help_text='dd/mm/yyyy hh:MM', verbose_name='Criada em')),
                ('atualizada_em', models.DateTimeField(auto_now_add=True, help_text='dd/mm/yyyy hh:MM', verbose_name='Atualizada')),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('publicada_em', models.DateTimeField(help_text='dd/mm/yyyy hh:MM', null=True, verbose_name='Publicada em')),
                ('publicada', models.BooleanField(default=False, verbose_name='Publicada')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_noticias.categoria')),
            ],
            options={
                'db_table': 'noticias',
            },
        ),
    ]
