# Generated by Django 5.1.1 on 2024-10-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0003_alter_noticia_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='publicada',
            field=models.BooleanField(default=False, editable=False, verbose_name='Publicada'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicada_em',
            field=models.DateTimeField(help_text='dd/mm/yyyy hh:MM', null=True, verbose_name='Publicada em'),
        ),
    ]
