# Generated by Django 5.1.1 on 2024-10-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0005_alter_noticia_publicada_alter_noticia_publicada_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='categoria',
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ManyToManyField(to='app_noticias.categoria'),
        ),
    ]
