# Generated by Django 5.1.2 on 2024-10-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
