# Generated by Django 5.1.1 on 2024-10-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0008_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'permissions': [('pode_publicar', 'Permissão atribuida à Editores para a publicação da Notícia')]},
        ),
    ]
