# Generated by Django 5.1.1 on 2024-10-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0010_categoria_imagem_noticia_num_visualizacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fonte_informacao',
            field=models.CharField(max_length=400, null=True, verbose_name='Fonte'),
        ),
    ]
